### ISSUE TITLE
Bug: Random GitHub Actions Test Failure

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2102]
**Describe the bug**
After pushing a commit, a set of GitHub Actions tests will run. Randomly, the `test (12.x)` and/or `test-rediscache-contactcache` tests will fail with the following errors:

**test (12.x):**
```
Summary of all failing tests
FAIL __test__/extensions/contact-loaders/csv-upload.test.js
  ● ingest-contact-loader method: csv-upload frontend › csv-upload:component handles custom fields

    TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null

      387 |
      388 | export async function unzipPayload(job) {
    > 389 |   return JSON.parse(await gunzip(Buffer.from(job.payload, "base64")));
          |                                         ^
      390 | }
      391 |
      392 | export async function assignTexters(job) {

      at _callee12$ (src/workers/jobs.js:389:41)
      at tryCatch (node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.<computed> [as next] (node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new F (node_modules/core-js/library/modules/_export.js:36:28)


Test Suites: 1 failed, 1 skipped, 71 passed, 72 of 73 total
Tests:       1 failed, 3 skipped, 651 passed, 655 total
Snapshots:   0 total
Time:        254.919s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**test-rediscache-contactcache:**
```
Summary of all failing tests
FAIL __test__/extensions/contact-loaders/csv-upload.test.js
  ● ingest-contact-loader method: csv-upload frontend › csv-upload:component handles custom fields

    TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received null

      387 |
      388 | export async function unzipPayload(job) {
    > 389 |   return JSON.parse(await gunzip(Buffer.from(job.payload, "base64")));
          |                                         ^
      390 | }
      391 |
      392 | export async function assignTexters(job) {

      at _callee12$ (src/workers/jobs.js:389:41)
      at tryCatch (node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.<computed> [as next] (node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new F (node_modules/core-js/library/modules/_export.js:36:28)


Test Suites: 1 failed, 1 skipped, 71 passed, 72 of 73 total
Tests:       1 failed, 3 skipped, 652 passed, 656 total
Snapshots:   0 total
Time:        265.533s
Ran all test suites.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPWRAP

      66 |   }
      67 |
    > 68 |   thinkyConn.r.redis = redis.createClient(redisSettings);
         |                              ^
      69 | } else if (process.env.REDIS_FAKE) {
      70 |   const fakeredis = require("fakeredis");
      71 |   bluebird.promisifyAll(fakeredis.RedisClient.prototype);

      at RedisClient.Object.<anonymous>.RedisClient.create_stream (node_modules/redis/index.js:196:31)
      at new RedisClient (node_modules/redis/index.js:121:10)
      at Object.createClient (node_modules/redis/index.js:1023:12)
      at Object.<anonymous> (src/server/models/thinky.js:68:30)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

This failure happens randomly, and the tests usually pass when re-running the workflow. It would be great to figure out what's causing this random failure.

**To Reproduce**
1. Create a new branch based off the `main` branch
2. Make a small change
3. Push your commit
4. Issue will happen randomly
5. You can also look at the Attempt 2 in this test run: https://github.com/MoveOnOrg/Spoke/runs/4720650032?check_suite_focus=true

**Expected behavior**
The `test (12.x)` and `test-rediscache-contactcache` tests should pass, or at least be consistent in passing/failing.

**Screenshots**
![image](https://user-images.githubusercontent.com/9382984/148296439-1c086411-4b13-4de8-9c43-f9d633715bd6.png)

**Platform (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Desktop
 - Version: 96.0.4664.110

**Comment by mau11** [comment]
This has been fixed in Spoke v14.
