### ISSUE TITLE
Dependencies: apollo-server-express security vulnerability

### ISSUE THREAD

**Issue by crayolakat** [StateVoicesNational/Spoke#2110]
**Describe the bug**
The `apollo-server-express` dependency has a security vulnerability as detected by Dependabot https://github.com/MoveOnOrg/Spoke/security/dependabot/package.json/apollo-server-express/open

However, the `apollo-server-express` library has changed a lot between our current version (1.2.0) and the updated version (2.14.2). Dependabot made a PR with this update: https://github.com/MoveOnOrg/Spoke/pull/2023. In that PR, Spoke will fail to run with this error:
```
8:49:05 PM server.1  |  backend error TypeError: (0 , _apolloServerE
8:49:05 PM server.1  |  >  xpress.graphqlExpress) is not a function
8:49:05 PM server.1  |      at Object.<anonymous> (/Users/kathynguyen/Documents/GitHub/S
8:49:05 PM server.1  |  >  poke/src/server/index.js:143:3)
8:49:05 PM server.1  |      at Module._compile (internal/modules/cjs/loader.js:999:30)
8:49:05 PM server.1  |      at loader (/Users/kathynguyen/Documents/GitHub/Spoke/node_mo
8:49:05 PM server.1  |  >  dules/babel-register/lib/node.js:144:5)
8:49:05 PM server.1  |      at Object.require.extensions.<computed> [as .js] (/Users/kat
8:49:05 PM server.1  |  >  hynguyen/Documents/GitHub/Spoke/node_modules/babel-register/lib/
8:49:05 PM server.1  |  >  node.js:154:7)
8:49:05 PM server.1  |      at Module.load (internal/modules/cjs/loader.js:863:32)
8:49:05 PM server.1  |      at Function.Module._load (internal/modules/cjs/loader.js:708
8:49:05 PM server.1  |  >  :14)
8:49:05 PM server.1  |      at Module.require (internal/modules/cjs/loader.js:887:19)
8:49:05 PM server.1  |      at require (internal/modules/cjs/helpers.js:74:18)
8:49:05 PM server.1  |      at Object.<anonymous> (/Users/kathynguyen/Documents/GitHub/S
8:49:05 PM server.1  |  >  poke/dev-tools/babel-run:4:1)
8:49:05 PM server.1  |      at Module._compile (internal/modules/cjs/loader.js:999:30)
8:49:05 PM server.1  |      at Object.Module._extensions..js (internal/modules/cjs/loade
8:49:05 PM server.1  |  >  r.js:1027:10)
8:49:05 PM server.1  |      at Module.load (internal/modules/cjs/loader.js:863:32)
8:49:05 PM server.1  |      at Function.Module._load (internal/modules/cjs/loader.js:708
8:49:05 PM server.1  |  >  :14)
8:49:05 PM server.1  |      at Function.executeUserEntryPoint [as runMain] (internal/mod
8:49:05 PM server.1  |  >  ules/run_main.js:60:12)
8:49:05 PM server.1  |      at internal/main/run_main_module.js:17:47
```

**To Reproduce**
1. Check out the code in this PR: https://github.com/MoveOnOrg/Spoke/pull/2023
2. Run `yarn install`
3. Run `yarn dev`. Error will be printed to the terminal after running `yarn dev`

**Expected behavior**
Spoke app should run successfully.

**Additional context**
This resource may be helpful in updating the Spoke codebase to support apollo-server-express 2.14.2 : https://dev.to/gloriamaris/apollo-server-express-10-to-20-fix-graphiqlexpress-and-graphiqlexpress-is-not-a-function-in-a-tutorial-by-xoor-41jn

**Comment by mau11** [comment]
This is no longer an issue as Apollo has been updated in Spoke v14.
