### ISSUE TITLE
Bug: Export Stuck at 0%

### ISSUE THREAD

**Issue by jb-cloud** [StateVoicesNational/Spoke#2264]
**Describe the bug**
After clicking Export Data in the UI the button changes to Exporting 0%. After more than a day the Exporting 0% is still observed and a link is not created. Exporting has worked as expected before.

**To Reproduce**
I'm not certain how to reproduce this as it has worked previously and there is nothing interesting about this export.

**Expected behavior**
A link to download would appear after refreshing.

**Screenshots**
<img width="686" alt="image" src="https://user-images.githubusercontent.com/26147861/221574076-51795b3a-63d0-49eb-b01c-3005c429c674.png">

**Platform (please complete the following information):**
 - OS: macOS 13.2
 - Browser: Firefox 110.0 (64-bit)
 - Desktop
 - Spoke Version 12.2
 - Heroku Hosted

**Additional context**
Heroku with Bucketeer. The Bucketeer credentials are in both the AWS and Bucketeer env vars. That seemed a little odd, but this has worked like this in the past with the same vars. 

The larger file of successful export would be ~63k rows. In Heroku I don't see any memory or load spikes.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/26147861/221575281-9c134ded-f951-4c90-8b79-33381306b6ed.png">

JOBS_SAME_PROCESS=1

Accessing the bucket from the aws cli, I don't see any files with the name of this campaign. 

After deleting the job from the job_request table and running FLUSHDB in redis, the button reappears in the UI, but clicking it produces the same result.

The name of the campaign contains a '/' which I think would be part of the export file name. I believe that would be problematic for aws _bucket_ names, but not an individual file's name.

**Comment by rock-the-vote** [comment]
Describe the bug

Perhaps similar issue? We are unable to export data from a campaign. After clicking the export button it appears to want to export but then I get an email with the error: 'No value provided for input HTTP label: Bucket.'

To Reproduce

Go to 'Campaigns'
Click on 'an individual campaign'
Click on 'Export Data'
Few minutes later an error email comes through and no download csv

Expected behavior

Download of csv to start via the browser

screenshots
![Screenshot 2024-07-24 at 10 03 32 AM](https://github.com/user-attachments/assets/0e58de60-9bef-405b-b272-b4e6a8ed3823)
![Screenshot 2024-07-24 at 10 03 52 AM](https://github.com/user-attachments/assets/c62ac721-47b9-425f-b6da-21cdf7ccdacc)
![Screenshot 2024-07-24 at 10 08 04 AM](https://github.com/user-attachments/assets/02260486-aef5-4f7e-aad0-d8dc9db20c42)


Platform (please complete the following information):

OS: macOS 14.5
Browser: all
Desktop
Version 14.0.0
Heroku / Bucketeer / Postgres / Mailgun / Papertrail

Additional context

logs read:
app/web.1 exportCampaign csvs 5665488 9138034
app/web.1 backend error Error: No value provided for input HTTP label: Bucket.
app/web.1     at resolvedPath (/spoke/node_modules/@smithy/smithy-client/dist-cjs/index.js:1125:11)
app/web.1     at /spoke/node_modules/@smithy/core/dist-cjs/index.js:392:57
app/web.1     at _RequestBuilder.build (/spoke/node_modules/@smithy/core/dist-cjs/index.js:358:7)
app/web.1 backend info Sending e-mail to ...

I did move all the BUCKETEER ENV VARs over to AWS_ VARs per documentation
AWS_REGION us-east-1
